org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true

android.useAndroidX=true
android.enableJetifier=true

MYAPP_UPLOAD_STORE_FILE=arise-release.keystore
MYAPP_UPLOAD_KEY_ALIAS=arise-key
MYAPP_UPLOAD_STORE_PASSWORD=
MYAPP_UPLOAD_KEY_PASSWORD=

newArchEnabled=false
hermesEnabled=true
